package ca.virology.baseByBase.gui.CodeHop;

import ca.virology.lib.util.gui.UITools;

import java.util.ArrayList;

/**
 * Class CodonTable
 * <p>
 * Stores an Array of ArrayLists.
 * <p>
 * The Array is indexed using the Lookup Value generated by the getLookupVal(char aminoAcid) function,
 * where each lookup value corresponds to an Amino Acid.
 * <p>
 * Each element of the Array (corresponding to a specific Amino Acid) contains an ArrayList.
 * <p>
 * Each ArrayList contains CodonTableEntry objects which correspond to indexed Amino Acid.
 */
public class CodonTable {

    public static ArrayList<CodonTableEntry>[] codonArray = (ArrayList<CodonTableEntry>[]) new ArrayList[21];

    public CodonTable() {
        setHomoSapien();
    }

    public static ArrayList<CodonTableEntry> getCodons(char AA) {
        return codonArray[getLookupVal(AA)];
    }

    public static String currentTableName = "Cowpox";

    /*
        returns a Lookup Value that allows the codonArray to be indexed
        correctly corresponding to the Amino Acid input
     */
    public static int getLookupVal(char AminoAcid){
        switch(AminoAcid){
            case 'A': return 0;
            case 'C': return 1;
            case 'D': return 2;
            case 'E': return 3;
            case 'F': return 4;
            case 'G': return 5;
            case 'H': return 6;
            case 'I': return 7;
            case 'K': return 8;
            case 'L': return 9;
            case 'M': return 10;
            case 'N': return 11;
            case 'P': return 12;
            case 'Q': return 13;
            case 'R': return 14;
            case 'S': return 15;
            case 'T': return 16;
            case 'V': return 17;
            case 'W': return 18;
            case 'Y': return 19;
            case '*': return 20; //stop
        }
        System.out.println("ERROR: getLookupVal() -- Bad Amino Acid Input");
        UITools.showWarning("Non amino acid character in sequence.", CodeHopWizard.getInstance());
        return -1;
    }


    public static char getAminoAcid(int lookupVal){
        switch(lookupVal){
            case 0:  return 'A';
            case 1:  return 'C';
            case 2:  return 'D';
            case 3:  return 'E';
            case 4:  return 'F';
            case 5:  return 'G';
            case 6:  return 'H';
            case 7:  return 'I';
            case 8:  return 'K';
            case 9:  return 'L';
            case 10: return 'M';
            case 11: return 'N';
            case 12: return 'P';
            case 13: return 'Q';
            case 14: return 'R';
            case 15: return 'S';
            case 16: return 'T';
            case 17: return 'V';
            case 18: return 'W';
            case 19: return 'Y';
            case 20: return '*'; //stop
        }
        System.out.println("ERROR: getAminoAcid() -- Bad lookupVal Input");
        UITools.showWarning("Non amino acid character in sequence.", CodeHopWizard.getInstance());
        return '-';
    }

    //Function looks through codontable for entry with matching codon and aa then replaces the 'probability' with argument 3
    public void updateCodonEntry(String aa, String codon, double probability) {
        char aacid = aa.charAt(0);
        int codonindex = getLookupVal(aacid);
        int i = 0;
        while (true) {
            if (codonArray[codonindex].get(i).codon.equals(codon)) {
                codonArray[codonindex].get(i).prob = probability;
                break;
            }
            if (i == codonArray[codonindex].size()) {
                break;
            }
            i += 1;
        }
    }

    //method generated by CodonTableToJava.py in Codehop folder
    public void setEnteroBacteriaT4() {
        for (int i = 0; i < codonArray.length; i++) {
            codonArray[i] = new ArrayList();
        }
        int lookupVal;

        lookupVal = getLookupVal('A');
        codonArray[lookupVal].add(new CodonTableEntry("GCT", 0.50, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCC", 0.08, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCA", 0.31, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCG", 0.10, "A"));
        lookupVal = getLookupVal('C');
        codonArray[lookupVal].add(new CodonTableEntry("TGT", 0.66, "C"));
        codonArray[lookupVal].add(new CodonTableEntry("TGC", 0.34, "C"));
        lookupVal = getLookupVal('E');
        codonArray[lookupVal].add(new CodonTableEntry("GAA", 0.85, "E"));
        codonArray[lookupVal].add(new CodonTableEntry("GAG", 0.15, "E"));
        lookupVal = getLookupVal('D');
        codonArray[lookupVal].add(new CodonTableEntry("GAT", 0.77, "D"));
        codonArray[lookupVal].add(new CodonTableEntry("GAC", 0.23, "D"));
        lookupVal = getLookupVal('G');
        codonArray[lookupVal].add(new CodonTableEntry("GGT", 0.47, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGC", 0.13, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGA", 0.33, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGG", 0.07, "G"));
        lookupVal = getLookupVal('F');
        codonArray[lookupVal].add(new CodonTableEntry("TTT", 0.75, "F"));
        codonArray[lookupVal].add(new CodonTableEntry("TTC", 0.25, "F"));
        lookupVal = getLookupVal('I');
        codonArray[lookupVal].add(new CodonTableEntry("ATT", 0.68, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATC", 0.15, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATA", 0.17, "I"));
        lookupVal = getLookupVal('H');
        codonArray[lookupVal].add(new CodonTableEntry("CAT", 0.77, "H"));
        codonArray[lookupVal].add(new CodonTableEntry("CAC", 0.23, "H"));
        lookupVal = getLookupVal('K');
        codonArray[lookupVal].add(new CodonTableEntry("AAA", 0.79, "K"));
        codonArray[lookupVal].add(new CodonTableEntry("AAG", 0.21, "K"));
        lookupVal = getLookupVal('*');
        codonArray[lookupVal].add(new CodonTableEntry("TAA", 0.60, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TGA", 0.33, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TAG", 0.07, "*"));
        lookupVal = getLookupVal('M');
        codonArray[lookupVal].add(new CodonTableEntry("ATG", 1.00, "M"));
        lookupVal = getLookupVal('L');
        codonArray[lookupVal].add(new CodonTableEntry("TTA", 0.37, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("TTG", 0.15, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTT", 0.25, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTC", 0.06, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTA", 0.09, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTG", 0.08, "L"));
        lookupVal = getLookupVal('N');
        codonArray[lookupVal].add(new CodonTableEntry("AAT", 0.74, "N"));
        codonArray[lookupVal].add(new CodonTableEntry("AAC", 0.26, "N"));
        lookupVal = getLookupVal('Q');
        codonArray[lookupVal].add(new CodonTableEntry("CAA", 0.66, "Q"));
        codonArray[lookupVal].add(new CodonTableEntry("CAG", 0.34, "Q"));
        lookupVal = getLookupVal('P');
        codonArray[lookupVal].add(new CodonTableEntry("CCT", 0.42, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCC", 0.03, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCA", 0.40, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCG", 0.15, "P"));
        lookupVal = getLookupVal('S');
        codonArray[lookupVal].add(new CodonTableEntry("TCT", 0.37, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCC", 0.06, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCA", 0.27, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCG", 0.06, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGT", 0.16, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGC", 0.08, "S"));
        lookupVal = getLookupVal('R');
        codonArray[lookupVal].add(new CodonTableEntry("CGT", 0.44, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGC", 0.13, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGA", 0.13, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGG", 0.03, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGA", 0.23, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGG", 0.04, "R"));
        lookupVal = getLookupVal('T');
        codonArray[lookupVal].add(new CodonTableEntry("ACT", 0.49, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACC", 0.11, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACA", 0.30, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACG", 0.09, "T"));
        lookupVal = getLookupVal('W');
        codonArray[lookupVal].add(new CodonTableEntry("TGG", 1.00, "W"));
        lookupVal = getLookupVal('V');
        codonArray[lookupVal].add(new CodonTableEntry("GTT", 0.50, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTC", 0.09, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTA", 0.32, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTG", 0.10, "V"));
        lookupVal = getLookupVal('Y');
        codonArray[lookupVal].add(new CodonTableEntry("TAT", 0.78, "Y"));
        codonArray[lookupVal].add(new CodonTableEntry("TAC", 0.22, "Y"));

        currentTableName = "Enterobacteria phage T4";

    }


    //method generated by CodonTableToJava.py in Codehop folder
    public void setEnteroBacteriaES18() {
        for (int i = 0; i < codonArray.length; i++) {
            codonArray[i] = new ArrayList();
        }
        int lookupVal;

        lookupVal = getLookupVal('A');
        codonArray[lookupVal].add(new CodonTableEntry("GCT", 0.26, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCC", 0.24, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCA", 0.29, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCG", 0.21, "A"));
        lookupVal = getLookupVal('C');
        codonArray[lookupVal].add(new CodonTableEntry("TGT", 0.33, "C"));
        codonArray[lookupVal].add(new CodonTableEntry("TGC", 0.67, "C"));
        lookupVal = getLookupVal('E');
        codonArray[lookupVal].add(new CodonTableEntry("GAA", 0.56, "E"));
        codonArray[lookupVal].add(new CodonTableEntry("GAG", 0.44, "E"));
        lookupVal = getLookupVal('D');
        codonArray[lookupVal].add(new CodonTableEntry("GAT", 0.56, "D"));
        codonArray[lookupVal].add(new CodonTableEntry("GAC", 0.44, "D"));
        lookupVal = getLookupVal('G');
        codonArray[lookupVal].add(new CodonTableEntry("GGT", 0.31, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGC", 0.32, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGA", 0.20, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGG", 0.17, "G"));
        lookupVal = getLookupVal('F');
        codonArray[lookupVal].add(new CodonTableEntry("TTT", 0.42, "F"));
        codonArray[lookupVal].add(new CodonTableEntry("TTC", 0.58, "F"));
        lookupVal = getLookupVal('I');
        codonArray[lookupVal].add(new CodonTableEntry("ATT", 0.44, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATC", 0.39, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATA", 0.17, "I"));
        lookupVal = getLookupVal('H');
        codonArray[lookupVal].add(new CodonTableEntry("CAT", 0.54, "H"));
        codonArray[lookupVal].add(new CodonTableEntry("CAC", 0.46, "H"));
        lookupVal = getLookupVal('K');
        codonArray[lookupVal].add(new CodonTableEntry("AAA", 0.58, "K"));
        codonArray[lookupVal].add(new CodonTableEntry("AAG", 0.42, "K"));
        lookupVal = getLookupVal('*');
        codonArray[lookupVal].add(new CodonTableEntry("TAA", 0.48, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TGA", 0.45, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TAG", 0.07, "*"));
        lookupVal = getLookupVal('M');
        codonArray[lookupVal].add(new CodonTableEntry("ATG", 1.00, "M"));
        lookupVal = getLookupVal('L');
        codonArray[lookupVal].add(new CodonTableEntry("TTA", 0.13, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("TTG", 0.11, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTT", 0.20, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTC", 0.13, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTA", 0.09, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTG", 0.34, "L"));
        lookupVal = getLookupVal('N');
        codonArray[lookupVal].add(new CodonTableEntry("AAT", 0.46, "N"));
        codonArray[lookupVal].add(new CodonTableEntry("AAC", 0.54, "N"));
        lookupVal = getLookupVal('Q');
        codonArray[lookupVal].add(new CodonTableEntry("CAA", 0.32, "Q"));
        codonArray[lookupVal].add(new CodonTableEntry("CAG", 0.68, "Q"));
        lookupVal = getLookupVal('P');
        codonArray[lookupVal].add(new CodonTableEntry("CCT", 0.23, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCC", 0.10, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCA", 0.35, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCG", 0.33, "P"));
        lookupVal = getLookupVal('S');
        codonArray[lookupVal].add(new CodonTableEntry("TCT", 0.17, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCC", 0.11, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCA", 0.25, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCG", 0.11, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGT", 0.13, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGC", 0.23, "S"));
        lookupVal = getLookupVal('R');
        codonArray[lookupVal].add(new CodonTableEntry("CGT", 0.23, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGC", 0.29, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGA", 0.13, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGG", 0.09, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGA", 0.14, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGG", 0.12, "R"));
        lookupVal = getLookupVal('T');
        codonArray[lookupVal].add(new CodonTableEntry("ACT", 0.21, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACC", 0.32, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACA", 0.28, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACG", 0.19, "T"));
        lookupVal = getLookupVal('W');
        codonArray[lookupVal].add(new CodonTableEntry("TGG", 1.00, "W"));
        lookupVal = getLookupVal('V');
        codonArray[lookupVal].add(new CodonTableEntry("GTT", 0.37, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTC", 0.19, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTA", 0.21, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTG", 0.23, "V"));
        lookupVal = getLookupVal('Y');
        codonArray[lookupVal].add(new CodonTableEntry("TAT", 0.49, "Y"));
        codonArray[lookupVal].add(new CodonTableEntry("TAC", 0.51, "Y"));

        currentTableName = "Enterobacteria phage ES18";
    }

    //method generated by CodonTableToJava.py in Codehop folder
    public void setEscherichiaColi() {
        for (int i = 0; i < codonArray.length; i++) {
            codonArray[i] = new ArrayList();
        }
        int lookupVal;

        lookupVal = getLookupVal('A');
        codonArray[lookupVal].add(new CodonTableEntry("GCT", 0.30, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCC", 0.17, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCA", 0.33, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCG", 0.21, "A"));
        lookupVal = getLookupVal('C');
        codonArray[lookupVal].add(new CodonTableEntry("TGT", 0.62, "C"));
        codonArray[lookupVal].add(new CodonTableEntry("TGC", 0.38, "C"));
        lookupVal = getLookupVal('E');
        codonArray[lookupVal].add(new CodonTableEntry("GAA", 0.62, "E"));
        codonArray[lookupVal].add(new CodonTableEntry("GAG", 0.38, "E"));
        lookupVal = getLookupVal('D');
        codonArray[lookupVal].add(new CodonTableEntry("GAT", 0.69, "D"));
        codonArray[lookupVal].add(new CodonTableEntry("GAC", 0.31, "D"));
        lookupVal = getLookupVal('G');
        codonArray[lookupVal].add(new CodonTableEntry("GGT", 0.19, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGC", 0.35, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGA", 0.21, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGG", 0.25, "G"));
        lookupVal = getLookupVal('F');
        codonArray[lookupVal].add(new CodonTableEntry("TTT", 0.80, "F"));
        codonArray[lookupVal].add(new CodonTableEntry("TTC", 0.20, "F"));
        lookupVal = getLookupVal('I');
        codonArray[lookupVal].add(new CodonTableEntry("ATT", 0.48, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATC", 0.14, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATA", 0.38, "I"));
        lookupVal = getLookupVal('H');
        codonArray[lookupVal].add(new CodonTableEntry("CAT", 0.90, "H"));
        codonArray[lookupVal].add(new CodonTableEntry("CAC", 0.10, "H"));
        lookupVal = getLookupVal('K');
        codonArray[lookupVal].add(new CodonTableEntry("AAA", 0.66, "K"));
        codonArray[lookupVal].add(new CodonTableEntry("AAG", 0.34, "K"));
        lookupVal = getLookupVal('*');
        codonArray[lookupVal].add(new CodonTableEntry("TAA", 0.35, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TGA", 0.62, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TAG", 0.03, "*"));
        lookupVal = getLookupVal('M');
        codonArray[lookupVal].add(new CodonTableEntry("ATG", 1.00, "M"));
        lookupVal = getLookupVal('L');
        codonArray[lookupVal].add(new CodonTableEntry("TTA", 0.22, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("TTG", 0.09, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTT", 0.23, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTC", 0.04, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTA", 0.02, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTG", 0.41, "L"));
        lookupVal = getLookupVal('N');
        codonArray[lookupVal].add(new CodonTableEntry("AAT", 0.71, "N"));
        codonArray[lookupVal].add(new CodonTableEntry("AAC", 0.29, "N"));
        lookupVal = getLookupVal('Q');
        codonArray[lookupVal].add(new CodonTableEntry("CAA", 0.50, "Q"));
        codonArray[lookupVal].add(new CodonTableEntry("CAG", 0.50, "Q"));
        lookupVal = getLookupVal('P');
        codonArray[lookupVal].add(new CodonTableEntry("CCT", 0.45, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCC", 0.04, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCA", 0.30, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCG", 0.20, "P"));
        lookupVal = getLookupVal('S');
        codonArray[lookupVal].add(new CodonTableEntry("TCT", 0.17, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCC", 0.13, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCA", 0.25, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCG", 0.10, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGT", 0.21, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGC", 0.14, "S"));
        lookupVal = getLookupVal('R');
        codonArray[lookupVal].add(new CodonTableEntry("CGT", 0.33, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGC", 0.14, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGA", 0.06, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGG", 0.18, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGA", 0.22, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGG", 0.06, "R"));
        lookupVal = getLookupVal('T');
        codonArray[lookupVal].add(new CodonTableEntry("ACT", 0.24, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACC", 0.19, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACA", 0.35, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACG", 0.23, "T"));
        lookupVal = getLookupVal('W');
        codonArray[lookupVal].add(new CodonTableEntry("TGG", 1.00, "W"));
        lookupVal = getLookupVal('V');
        codonArray[lookupVal].add(new CodonTableEntry("GTT", 0.28, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTC", 0.15, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTA", 0.22, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTG", 0.35, "V"));
        lookupVal = getLookupVal('Y');
        codonArray[lookupVal].add(new CodonTableEntry("TAT", 0.83, "Y"));
        codonArray[lookupVal].add(new CodonTableEntry("TAC", 0.17, "Y"));

        currentTableName = "Escherichia coli O157";

    }

    //method generated by CodonTableToJava.py in Codehop folder
    public void setMusMusculus() {
        for (int i = 0; i < codonArray.length; i++) {
            codonArray[i] = new ArrayList();
        }
        int lookupVal;

        lookupVal = getLookupVal('A');
        codonArray[lookupVal].add(new CodonTableEntry("GCT", 0.29, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCC", 0.38, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCA", 0.23, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCG", 0.09, "A"));
        lookupVal = getLookupVal('C');
        codonArray[lookupVal].add(new CodonTableEntry("TGT", 0.48, "C"));
        codonArray[lookupVal].add(new CodonTableEntry("TGC", 0.52, "C"));
        lookupVal = getLookupVal('E');
        codonArray[lookupVal].add(new CodonTableEntry("GAA", 0.41, "E"));
        codonArray[lookupVal].add(new CodonTableEntry("GAG", 0.59, "E"));
        lookupVal = getLookupVal('D');
        codonArray[lookupVal].add(new CodonTableEntry("GAT", 0.45, "D"));
        codonArray[lookupVal].add(new CodonTableEntry("GAC", 0.55, "D"));
        lookupVal = getLookupVal('G');
        codonArray[lookupVal].add(new CodonTableEntry("GGT", 0.18, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGC", 0.33, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGA", 0.26, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGG", 0.23, "G"));
        lookupVal = getLookupVal('F');
        codonArray[lookupVal].add(new CodonTableEntry("TTT", 0.44, "F"));
        codonArray[lookupVal].add(new CodonTableEntry("TTC", 0.56, "F"));
        lookupVal = getLookupVal('I');
        codonArray[lookupVal].add(new CodonTableEntry("ATT", 0.34, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATC", 0.50, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATA", 0.16, "I"));
        lookupVal = getLookupVal('H');
        codonArray[lookupVal].add(new CodonTableEntry("CAT", 0.41, "H"));
        codonArray[lookupVal].add(new CodonTableEntry("CAC", 0.59, "H"));
        lookupVal = getLookupVal('K');
        codonArray[lookupVal].add(new CodonTableEntry("AAA", 0.39, "K"));
        codonArray[lookupVal].add(new CodonTableEntry("AAG", 0.61, "K"));
        lookupVal = getLookupVal('*');
        codonArray[lookupVal].add(new CodonTableEntry("TAA", 0.28, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TGA", 0.49, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TAG", 0.23, "*"));
        lookupVal = getLookupVal('M');
        codonArray[lookupVal].add(new CodonTableEntry("ATG", 1.00, "M"));
        lookupVal = getLookupVal('L');
        codonArray[lookupVal].add(new CodonTableEntry("TTA", 0.07, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("TTG", 0.13, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTT", 0.13, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTC", 0.20, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTA", 0.08, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTG", 0.39, "L"));
        lookupVal = getLookupVal('N');
        codonArray[lookupVal].add(new CodonTableEntry("AAT", 0.43, "N"));
        codonArray[lookupVal].add(new CodonTableEntry("AAC", 0.57, "N"));
        lookupVal = getLookupVal('Q');
        codonArray[lookupVal].add(new CodonTableEntry("CAA", 0.26, "Q"));
        codonArray[lookupVal].add(new CodonTableEntry("CAG", 0.74, "Q"));
        lookupVal = getLookupVal('P');
        codonArray[lookupVal].add(new CodonTableEntry("CCT", 0.31, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCC", 0.30, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCA", 0.29, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCG", 0.10, "P"));
        lookupVal = getLookupVal('S');
        codonArray[lookupVal].add(new CodonTableEntry("TCT", 0.20, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCC", 0.22, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCA", 0.14, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCG", 0.05, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGT", 0.15, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGC", 0.24, "S"));
        lookupVal = getLookupVal('R');
        codonArray[lookupVal].add(new CodonTableEntry("CGT", 0.08, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGC", 0.17, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGA", 0.12, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGG", 0.19, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGA", 0.22, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGG", 0.22, "R"));
        lookupVal = getLookupVal('T');
        codonArray[lookupVal].add(new CodonTableEntry("ACT", 0.25, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACC", 0.35, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACA", 0.29, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACG", 0.10, "T"));
        lookupVal = getLookupVal('W');
        codonArray[lookupVal].add(new CodonTableEntry("TGG", 1.00, "W"));
        lookupVal = getLookupVal('V');
        codonArray[lookupVal].add(new CodonTableEntry("GTT", 0.17, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTC", 0.25, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTA", 0.12, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTG", 0.46, "V"));
        lookupVal = getLookupVal('Y');
        codonArray[lookupVal].add(new CodonTableEntry("TAT", 0.43, "Y"));
        codonArray[lookupVal].add(new CodonTableEntry("TAC", 0.57, "Y"));

        currentTableName = "Mus musculus";
    }

    //method generated by CodonTableToJava.py in Codehop folder
    public void setHomoSapien() {
        for (int i = 0; i < codonArray.length; i++) {
            codonArray[i] = new ArrayList();
        }
        int lookupVal;

        lookupVal = getLookupVal('A');
        codonArray[lookupVal].add(new CodonTableEntry("GCT", 0.27, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCC", 0.40, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCA", 0.23, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCG", 0.11, "A"));
        lookupVal = getLookupVal('C');
        codonArray[lookupVal].add(new CodonTableEntry("TGT", 0.46, "C"));
        codonArray[lookupVal].add(new CodonTableEntry("TGC", 0.54, "C"));
        lookupVal = getLookupVal('E');
        codonArray[lookupVal].add(new CodonTableEntry("GAA", 0.42, "E"));
        codonArray[lookupVal].add(new CodonTableEntry("GAG", 0.58, "E"));
        lookupVal = getLookupVal('D');
        codonArray[lookupVal].add(new CodonTableEntry("GAT", 0.46, "D"));
        codonArray[lookupVal].add(new CodonTableEntry("GAC", 0.54, "D"));
        lookupVal = getLookupVal('G');
        codonArray[lookupVal].add(new CodonTableEntry("GGT", 0.16, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGC", 0.34, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGA", 0.25, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGG", 0.25, "G"));
        lookupVal = getLookupVal('F');
        codonArray[lookupVal].add(new CodonTableEntry("TTT", 0.46, "F"));
        codonArray[lookupVal].add(new CodonTableEntry("TTC", 0.54, "F"));
        lookupVal = getLookupVal('I');
        codonArray[lookupVal].add(new CodonTableEntry("ATT", 0.36, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATC", 0.47, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATA", 0.17, "I"));
        lookupVal = getLookupVal('H');
        codonArray[lookupVal].add(new CodonTableEntry("CAT", 0.42, "H"));
        codonArray[lookupVal].add(new CodonTableEntry("CAC", 0.58, "H"));
        lookupVal = getLookupVal('K');
        codonArray[lookupVal].add(new CodonTableEntry("AAA", 0.43, "K"));
        codonArray[lookupVal].add(new CodonTableEntry("AAG", 0.57, "K"));
        lookupVal = getLookupVal('*');
        codonArray[lookupVal].add(new CodonTableEntry("TAA", 0.30, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TGA", 0.47, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TAG", 0.24, "*"));
        lookupVal = getLookupVal('M');
        codonArray[lookupVal].add(new CodonTableEntry("ATG", 1.00, "M"));
        lookupVal = getLookupVal('L');
        codonArray[lookupVal].add(new CodonTableEntry("TTA", 0.08, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("TTG", 0.13, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTT", 0.13, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTC", 0.20, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTA", 0.07, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTG", 0.40, "L"));
        lookupVal = getLookupVal('N');
        codonArray[lookupVal].add(new CodonTableEntry("AAT", 0.47, "N"));
        codonArray[lookupVal].add(new CodonTableEntry("AAC", 0.53, "N"));
        lookupVal = getLookupVal('Q');
        codonArray[lookupVal].add(new CodonTableEntry("CAA", 0.27, "Q"));
        codonArray[lookupVal].add(new CodonTableEntry("CAG", 0.73, "Q"));
        lookupVal = getLookupVal('P');
        codonArray[lookupVal].add(new CodonTableEntry("CCT", 0.29, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCC", 0.32, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCA", 0.28, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCG", 0.11, "P"));
        lookupVal = getLookupVal('S');
        codonArray[lookupVal].add(new CodonTableEntry("TCT", 0.19, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCC", 0.22, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCA", 0.15, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCG", 0.05, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGT", 0.15, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGC", 0.24, "S"));
        lookupVal = getLookupVal('R');
        codonArray[lookupVal].add(new CodonTableEntry("CGT", 0.08, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGC", 0.18, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGA", 0.11, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGG", 0.20, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGA", 0.21, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGG", 0.21, "R"));
        lookupVal = getLookupVal('T');
        codonArray[lookupVal].add(new CodonTableEntry("ACT", 0.25, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACC", 0.36, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACA", 0.28, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACG", 0.11, "T"));
        lookupVal = getLookupVal('W');
        codonArray[lookupVal].add(new CodonTableEntry("TGG", 1.00, "W"));
        lookupVal = getLookupVal('V');
        codonArray[lookupVal].add(new CodonTableEntry("GTT", 0.18, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTC", 0.24, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTA", 0.12, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTG", 0.46, "V"));
        lookupVal = getLookupVal('Y');
        codonArray[lookupVal].add(new CodonTableEntry("TAT", 0.44, "Y"));
        codonArray[lookupVal].add(new CodonTableEntry("TAC", 0.56, "Y"));


        currentTableName = "Homo sapien";
    }

    public void setCowPox() {

        //initialize each codonArray element as an empty ArrayList
        for (int i = 0; i < codonArray.length; i++) {
            codonArray[i] = new ArrayList();
        }

        int lookupVal = getLookupVal('A');
        codonArray[lookupVal].add(new CodonTableEntry("GCT", 0.36, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCC", 0.16, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCA", 0.31, "A"));
        codonArray[lookupVal].add(new CodonTableEntry("GCG", 0.17, "A"));

        lookupVal = getLookupVal('R');
        codonArray[lookupVal].add(new CodonTableEntry("CGT", 0.16, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGC", 0.06, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGA", 0.13, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("CGG", 0.04, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGA", 0.51, "R"));
        codonArray[lookupVal].add(new CodonTableEntry("AGG", 0.09, "R"));

        lookupVal = getLookupVal('N');
        codonArray[lookupVal].add(new CodonTableEntry("AAT", 0.72, "N"));
        codonArray[lookupVal].add(new CodonTableEntry("AAC", 0.28, "N"));

        lookupVal = getLookupVal('D');
        codonArray[lookupVal].add(new CodonTableEntry("GAT", 0.74, "D"));
        codonArray[lookupVal].add(new CodonTableEntry("GAC", 0.26, "D"));

        lookupVal = getLookupVal('C');
        codonArray[lookupVal].add(new CodonTableEntry("TGT", 0.76, "C"));
        codonArray[lookupVal].add(new CodonTableEntry("TGC", 0.24, "C"));

        lookupVal = getLookupVal('Q');
        codonArray[lookupVal].add(new CodonTableEntry("CAA", 0.70, "Q"));
        codonArray[lookupVal].add(new CodonTableEntry("CAG", 0.30, "Q"));

        lookupVal = getLookupVal('E');
        codonArray[lookupVal].add(new CodonTableEntry("GAA", 0.73, "E"));
        codonArray[lookupVal].add(new CodonTableEntry("GAG", 0.27, "E"));

        lookupVal = getLookupVal('G');
        codonArray[lookupVal].add(new CodonTableEntry("GGT", 0.33, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGC", 0.08, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGA", 0.53, "G"));
        codonArray[lookupVal].add(new CodonTableEntry("GGG", 0.06, "G"));

        lookupVal = getLookupVal('H');
        codonArray[lookupVal].add(new CodonTableEntry("CAT", 0.72, "H"));
        codonArray[lookupVal].add(new CodonTableEntry("CAC", 0.28, "H"));

        lookupVal = getLookupVal('I');
        codonArray[lookupVal].add(new CodonTableEntry("ATT", 0.39, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATC", 0.21, "I"));
        codonArray[lookupVal].add(new CodonTableEntry("ATA", 0.40, "I"));

        lookupVal = getLookupVal('L');
        codonArray[lookupVal].add(new CodonTableEntry("TTA", 0.27, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("TTG", 0.21, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTT", 0.14, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTC", 0.07, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTA", 0.22, "L"));
        codonArray[lookupVal].add(new CodonTableEntry("CTG", 0.08, "L"));

        lookupVal = getLookupVal('K');
        codonArray[lookupVal].add(new CodonTableEntry("AAA", 0.67, "K"));
        codonArray[lookupVal].add(new CodonTableEntry("AAG", 0.33, "K"));

        lookupVal = getLookupVal('M');
        codonArray[lookupVal].add(new CodonTableEntry("ATG", 1.00, "M"));

        lookupVal = getLookupVal('F');
        codonArray[lookupVal].add(new CodonTableEntry("TTT", 0.68, "F"));
        codonArray[lookupVal].add(new CodonTableEntry("TTC", 0.32, "F"));

        lookupVal = getLookupVal('P');
        codonArray[lookupVal].add(new CodonTableEntry("CCT", 0.31, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCC", 0.13, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCA", 0.39, "P"));
        codonArray[lookupVal].add(new CodonTableEntry("CCG", 0.17, "P"));

        lookupVal = getLookupVal('S');
        codonArray[lookupVal].add(new CodonTableEntry("TCT", 0.30, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCC", 0.12, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCA", 0.21, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("TCG", 0.10, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGT", 0.20, "S"));
        codonArray[lookupVal].add(new CodonTableEntry("AGC", 0.07, "S"));

        lookupVal = getLookupVal('T');
        codonArray[lookupVal].add(new CodonTableEntry("ACT", 0.38, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACC", 0.13, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACA", 0.36, "T"));
        codonArray[lookupVal].add(new CodonTableEntry("ACG", 0.13, "T"));

        lookupVal = getLookupVal('W');
        codonArray[lookupVal].add(new CodonTableEntry("TGG", 1.00, "W"));

        lookupVal = getLookupVal('Y');
        codonArray[lookupVal].add(new CodonTableEntry("TAT", 0.69, "Y"));
        codonArray[lookupVal].add(new CodonTableEntry("TAC", 0.31, "Y"));

        lookupVal = getLookupVal('V');
        codonArray[lookupVal].add(new CodonTableEntry("GTT", 0.32, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTC", 0.16, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTA", 0.38, "V"));
        codonArray[lookupVal].add(new CodonTableEntry("GTG", 0.14, "V"));

        lookupVal = getLookupVal('*');
        codonArray[lookupVal].add(new CodonTableEntry("TAA", 0.56, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TGA", 0.21, "*"));
        codonArray[lookupVal].add(new CodonTableEntry("TAG", 0.23, "*"));

        currentTableName = "Cowpox virus";
    }

    public String[][] getTableContents() {
        String[][] contents = new String[64][3];
        int insertAt = 0;
        for (int i = 0; i < 21; i++) {
            for (int j = 0; j < codonArray[i].size(); j++) {
                String codon = codonArray[i].get(j).codon;
                String prob = String.valueOf(codonArray[i].get(j).prob);
                String aa = codonArray[i].get(j).aa;
                contents[insertAt][0] = aa;
                contents[insertAt][1] = codon;
                contents[insertAt][2] = prob;
                insertAt += 1;
            }
        }
        return contents;
    }

    /*
    Very similar to updateCodonEntry(), but only requires two arguments.
    Third argument in updateCodonEntry() needs a method call to compute AA from codon.
     */
    public void modify(String codon, double prob) {
        for (int i = 0; i < 21; i++) {
            for (int j = 0; j < codonArray[i].size(); j++) {
                if (codonArray[i].get(j).codon.equals(codon)) {
                    codonArray[i].get(j).prob = prob;
                }
            }
        }
    }

    public static String getName() {
        return "codon table name";
    }
}
